/* export const getListaProveedoresAction = async ( {commit}  ) => {
    // TODO: Call service
    const data = [
        {
          rfc: "ABCDE1234",
          nombreEmpresa: "Empresa",
          razonSocail:"Razón socail",
          tipoPersona:"Física",
          nombreContacto:"Pablito Pérez",
          informacionValidada: "Sí",
          documentosVigentes: "Sí",
        },
        {
          rfc: "RFCASD1234",
          nombreEmpresa: "Empresa",
          razonSocail:"Razón socail",
          tipoPersona:"Física",
          nombreContacto:"Pablito Pérez",
          informacionValidada: "Sí",
          documentosVigentes: "Sí",
        },
        {
          rfc: "RFCASD1234",
          nombreEmpresa: "Empresa",
          razonSocail:"Razón socail",
          tipoPersona:"Física",
          nombreContacto:"Pablito Pérez",
          informacionValidada: "Sí",
          documentosVigentes: "Sí",
        },
        {
          rfc: "RFCASD1234",
          nombreEmpresa: "Empresa",
          razonSocail:"Razón socail",
          tipoPersona:"Física",
          nombreContacto:"Pablito Pérez",
          informacionValidada: "Sí",
          documentosVigentes: "Sí",
        },
        {
          rfc: "RFCASD1234",
          nombreEmpresa: "Empresa",
          razonSocail:"Razón socail",
          tipoPersona:"Física",
          nombreContacto:"Pablito Pérez",
          informacionValidada: "Sí",
          documentosVigentes: "Sí",
        },
        {
          rfc: "RFCASD1234",
          nombreEmpresa: "Empresa",
          razonSocail:"Razón socail",
          tipoPersona:"Física",
          nombreContacto:"Pablito Pérez",
          informacionValidada: "Sí",
          documentosVigentes: "Sí",
        },
        {
          rfc: "RFCASD1234",
          nombreEmpresa: "Empresa",
          razonSocail:"Razón socail",
          tipoPersona:"Física",
          nombreContacto:"Pablito Pérez",
          informacionValidada: "Sí",
          documentosVigentes: "Sí",
        },
        {
          rfc: "RFCASD1234",
          nombreEmpresa: "Empresa",
          razonSocail:"Razón socail",
          tipoPersona:"Física",
          nombreContacto:"Pablito Pérez",
          informacionValidada: "Sí",
          documentosVigentes: "Sí",
        },
        {
          rfc: "RFCASD1234",
          nombreEmpresa: "Empresa",
          razonSocail:"Razón socail",
          tipoPersona:"Física",
          nombreContacto:"Pablito Pérez",
          informacionValidada: "Sí",
          documentosVigentes: "Sí",
        },
        {
          rfc: "RFCASD1234",
          nombreEmpresa: "Empresa",
          razonSocail:"Razón socail",
          tipoPersona:"Física",
          nombreContacto:"Pablito Pérez",
          informacionValidada: "Sí",
          documentosVigentes: "Sí",
        },
        {
          rfc: "RFCASD1234",
          nombreEmpresa: "Empresa",
          razonSocail:"Razón socail",
          tipoPersona:"Física",
          nombreContacto:"Pablito Pérez",
          informacionValidada: "Sí",
          documentosVigentes: "Sí",
        },
        {
          rfc: "RFCASD1234",
          nombreEmpresa: "Empresa",
          razonSocail:"Razón socail",
          tipoPersona:"Física",
          nombreContacto:"Pablito Pérez",
          informacionValidada: "Sí",
          documentosVigentes: "Sí",
        },
      ]
    commit('setListaProveedores',data)
} */

